### ISSUE TITLE
SSL3_GET_RECORD error

### ISSUE THREAD

**Issue by shsu** [wildbit/postmark.js#12] opened 2017-01-02 02:54 UTC
Postmark Node.js library on Node v5.12 seems to hit this issue intermittently, it looks like it may be due to that postmark API does not support insecure versions of SSL. The solution to this problem is to enforce `TLSv1` on all requests as shown in this [comment](https://github.com/nodejs/node/issues/3692#issuecomment-200000499)

```
> process.versions
{ http_parser: '2.7.0',
  node: '5.12.0',
  v8: '4.6.85.32',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2h' }
```

Ref:
https://github.com/openssl/openssl/pull/852
https://github.com/nodejs/node/issues/4270 (milestone set to v8)

**Comment by atheken** [comment] 2017-01-03 19:37
@shsu Hi! Thanks for the info. We recently switched to use the `request` module, which introduced this problem for some folks. We'll get it fixed and push out an update.

**Comment by shsu** [comment] 2017-01-04 00:33
Thanks @atheken, please reference this issue when it is resolved.

Thanks

**Comment by ibalosh** [comment] 2018-11-06 16:27
Hi @shsu 

could you share details if you still see this issue? Version of request was updated, among other updates we made recently to the library while porting it to Typescript.

**Comment by ibalosh** [comment] 2018-11-13 10:14
closing since we can't reproduce it anymore, if it re-appears we will check it out more in depth

**Closed by ibalosh** 2018-11-13 10:14 UTC
