### ISSUE TITLE
Problems Sending Batch Emails & Parsing API Error.

### ISSUE THREAD

**Issue by zjr** [wildbit/postmark.js#55] opened 2019-08-19 22:05 UTC
I was trying to send emails using `ServerClient.sendEmailBatch`. I had some batches failing and giving me an error like this:

```js
{
  message: "PostmarkError",
  code: 0,
  statusCode: 0
}
```

I modified the installed Postmark NPM module to log out the error earlier and it spewed back a lot of base64 encoded attachment data.

So my problem is twofold:

1. The NPM module doesn't seem to be parsing API errors properly.
2. I think I am sending batches that are exceeding some kind of byte size constraint. I have attachments on each of the messages and they're duplicate attachments.
  2a. Is there a better way to deal with the attachments?
  2b. Is there some kind of byte size limit?

Thank you, will try to provide more information tomorrow.

**Comment by ibalosh** [comment] 2019-08-20 10:47
Hi @zjr 

- (1)  Could you share the response you got and we will take a look? Also any details on how you got the error would be great (batch sizes, etc)
- (2) There is a limit in Postmark for size of emails and attachments, so if you are sending big attachments you might get an error. Please contact our support at https://postmarkapp.com/contact for details about size limits.

In case you are sending very big attachments, might be better to store them externaly and link them in your emails.

Also in case you are using batches + very big attachments, you might be reaching your network limits when using the Postmark client, so you might be getting timeouts.

**Comment by zjr** [comment] 2019-08-20 14:32
Hi @ibalosh 

### Question № 1

More Details:

- I was sending approximately 18 emails in a batch.
- Each email had the same 4 attachments with a total size of ~3.6MB.
- We could guess that my request body was something in the ~65MB range.

The error received from the client looked like this:
```js
{ PostmarkError
    at ErrorHandler.buildError (/home/ubuntu/apps/seadra/source/node_modules/postmark/dist/client/ErrorHandler.js:34:16)
    at ErrorHandler.generateError (/home/ubuntu/apps/seadra/source/node_modules/postmark/dist/client/ErrorHandler.js:23:25)
    at /home/ubuntu/apps/seadra/source/node_modules/postmark/dist/client/BaseClient.js:86:38
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) statusCode: 0, code: 0, name: 'PostmarkError' }
```
The response I got from the API is a bit harder to dig through…

- I do see that I seem to have gotten a server called `'unicorns-double-rainbow'` (nice [🌈🦄🌈]).
- `writelen` might suggest content was closer to 80MB (encoding maybe?).
- I might have actually gotten a 404 (I'm not using the API directly so don't think this should happen)?
- POST went to `//email/batch` (double slash intentional)
- Yeah it definitely sends to `https://api.postmarkapp.com//email/batch` and it very much looks like that 404'd.
- That's all I've got. If there's any more of a message it didn't get parsed into my logs, my response says 404, message "Not Found".

here's a sample
```
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers:.
 { server: 'unicorns-double-rainbow',
   'x-powered-by': 'ASP.NET',
   date: 'Mon, 19 Aug 2019 21:00:13 GMT',
   connection: 'close',
   'content-length': '0' },
rawHeaders:.
 [ 'Server',
   'unicorns-double-rainbow',
   'X-Powered-By',
   'ASP.NET',
   'Date',
   'Mon, 19 Aug 2019 21:00:13 GMT',
   'Connection',
   'close',
   'Content-Length',
   '0' ],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 404,
statusMessage: 'Not Found',
client:.
 TLSSocket {
   _tlsOptions:.
    { pipe: false,
      secureContext: [Object],
      isServer: false,
      requestCert: true,
      rejectUnauthorized: true,
      session: undefined,
      NPNProtocols: undefined,
      ALPNProtocols: undefined,
      requestOCSP: undefined },
   _secureEstablished: true,
   _securePending: false,
   _newSessionPending: false,
   _controlReleased: true,
   _SNICallback: null,
   servername: 'api.postmarkapp.com',
```

### Question № 2

- Whether my payload was 60MB or 80MB, I understand this is a rather large request body.
- The individual attachments should not exceed general attachments, however.
- I do in fact link to the attachments instead of putting them in the email when they exceed normal limits.
- My client, in this case, prefers attachments in the emails when possible.
- Given that I can get the same effect by looping the emails and sending them to your API individually, it seems like it might be nice to be able to do this in a batch _for both our sakes_.
- Maybe there could be a way to include common attachments that are duplicated on each email? I feel like this would be a somewhat frequent use-case and could save your servers a fair amount of trouble as I could potentially be hitting you API with < ~5MB of data instead of 60-80MB over 18 different separate requests.
- It doesn't appear I'm hitting network limits as I can send the messages individually without issue.

Thanks for taking the time to look into this!

**Comment by ibalosh** [comment] 2019-08-21 08:31
Hey @zjr 

thank you for all the details! Unfortunately, I haven't been able to reproduce this yet  :(

https://api.postmarkapp.com//email/batch is still a valid way to reach endpoint - can be checked by something like: curl -X POST "https://api.postmarkapp.com//email/batch" -d "" -H "Content-Type: application/json"

I will see to check this in more details in following days, that size should still be ok for sending. Meanwhile, could you share the following, it will speed up identifying what could cause this:

- node version you are using
- the language you are using (are you using Typescript, JS, which version?)
- maybe code snippet (without credentials) , of the way you do the call (whether you use promise, callback, etc)
- does it work with different node version?

Also, does the same call work without attachments?

**Comment by zjr** [comment] 2019-08-21 14:35
Hi @ibalosh,

Answering your questions…

> * node version you are using

This particular application is actually on v8.15.1, so, a little behind.

> * the language you are using (are you using Typescript, JS, which version?)

Just plain JavaScript… version I guess ES2019 (you probably mean this more for TS)?

> * maybe code snippet (without credentials) , of the way you do the call (whether you use promise, callback, etc)

Using the promise, looks like this:
```js
const getMailOpts = opts => To => ({
  To,
  From: 'alerts@sevensondailyreport.com',
  Subject: 'Alert from SES',
  ...opts
});

module.exports = {
  send(addresses, contentOpts) {
    if (!Array.isArray(addresses)) addresses = [addresses];

    addresses = addresses.filter(Boolean);

    if (!addresses.length) return;

    return client
      .sendEmailBatch(addresses.map(getMailOpts(contentOpts)))
      .then(console.log)
      .catch(console.error);
  }
};
```

> * does it work with different node version?

I can't replicate the issue locally and I don't want to test it in production.

> Also, does the same call work without attachments?

Same for previous question.

I tested this locally with a few attachments before I deployed it the first time and I didn't have any issues. After I deployed to production I was seeing these errors logged for larger production objects so I made the guess it had to do with the size. I've now tested locally with similar conditions, however, and am not seeing the issue reproduced.

I can tell you that the I was getting errors like this at _around_ 2019-08-19 16:41 EDT. I say around because it looks like the server clock has drifted substantially. I was definitely receiving 404 responses and I am _very_ confused by that. Is it possible you have something logged?

I'm hesitant to try this again in production for probably obvious reasons.

**Comment by ibalosh** [comment] 2019-08-29 11:40
Hi @zjr 

sorry for bit late response. We did not experience any issues at that time and haven't seen any reports for this type of issue.

We haven't been able yet to replicate it, but we will take another look at it soon.

**Comment by ibalosh** [comment] 2019-09-19 10:20
marking resolved since we haven't seen the issue and were not able to reproduce it.

We released meanwhile a small update that will give bit more details regarding errors like 404.

**Comment by ibalosh** [comment] 2019-09-19 10:56
hm, just found a specific test case in which I could reproduce it, will reopen and investigate it further

**Comment by ibalosh** [comment] 2019-09-19 13:26
Hi @zjr 

I have reproduced the problem. It has to do with batch size. If you keep the request body under 50mb, you should not encounter the issue.

I will contact the API team to see about the limit, for more details feel free to contact our support team. Since it's not a library limitation, will close the issue.

**Closed by ibalosh** 2019-09-19 13:26 UTC

**Comment by zjr** [comment] 2019-09-19 13:29
Is there somewhere else I could open an issue or put in a feature request to have attachments spread across multiple messages? I.e. when I have the same attachment that needs to be sent in several messages.

**Comment by ibalosh** [comment] 2019-09-19 13:33
Hi @zjr 

of course. Contact our support team at https://postmarkapp.com/contact and they will handle the rest.

Igor

**Comment by manishsundriyal** [comment] 2021-02-01 08:00
I have faced the same issue. It occurs when we exceed the payload size limit (50MB). 
`Buffer.byteLength(JSON.stringify(emailList), 'utf8')`
As @zjr said, this issue could have been resolved if there was an option to not replicate the same HTMLBody, TextBody, and Attachments in the body. As these impact a lot in the overall size.
