### ISSUE TITLE
Multiple fields missing from TemplatedMessage constructor

### ISSUE THREAD

**Issue by tsongas** [wildbit/postmark.js#88] opened 2021-12-30 05:57 UTC
```
export declare class TemplatedMessage {
    TemplateId?: number;
    TemplateAlias?: string;
    TemplateModel: object;
    InlineCss?: boolean;
    From: string;
    To?: string;
    Cc?: string;
    Bcc?: string;
    ReplyTo?: string;
    MessageStream?: string;
    Tag?: string;
    TrackOpens?: boolean;
    TrackLinks?: LinkTrackingOptions;
    Headers?: Header[];
    Metadata?: Hash<string>;
    Attachments?: Attachment[];
    constructor(from: string, templateIdOrAlias: (number | string), templateModel: object, to?: string, cc?: string, bcc?: string, replyTo?: string, tag?: string, trackOpens?: boolean, trackLinks?: LinkTrackingOptions, headers?: Header[], attachments?: Attachment[]);
}
```

**Comment by tsongas** [comment] 2022-01-02 19:20
`MessageStream` and `Metadata` are both missing from the constructor and would be helpful to have.

**Comment by ibalosh** [comment] 2022-01-03 09:52
duplicate of https://github.com/wildbit/postmark.js/issues/50

**Closed by ibalosh** 2022-01-03 09:52 UTC
